server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://10.1.17.191:5432/postgres
    port: 5432
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  groovy:
    template:
      check-template-location: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: autotimemanager@gmail.com
    password: odxuiequxzbhlnpg
    properties:
      mail:
        smtp:
          auth: =true
          starttls:
            enable: true